### ISSUE TITLE
the use of aggregated volume

### ISSUE THREAD

**Issue by shuxiusuxiu** [Tai-Wang/Depth-from-Motion#22]
Thanks for your excellent work!
The boost of performance is due in the aggregation of mono-volume and stereo-volume according to the paper, however, I found that the aggregated volume is only used for predicting depth and used as the weight of image features. And only the stereo-volume is used for generating BEV features. 
I am kind of confused, have you ever tried to use the hybrid-volume to generate BEV features?

**Comment by Tai-Wang** [comment]
Good point. We tried before, but it did not further improve the performance.

Because we finally used the concatenation of lifted semantic features (weighted by the predicted depth distribution) and stereo cost volume in the current implementation, I guess the former component plays an important role in the final detection such that the change of stereo cost volume does not affect the performance much.

From another perspective, due to the fluctuation of KITTI performance, we can not get confident conclusions about which implementation is better, which may be better studied on nuScenes and Waymo in the future.

**Comment by shuxiusuxiu** [comment]
Thanks for your reply!
To put it another way, the key point is the concatenation of semantic features which are weighted by the distribution of depth. 
And the depth distribution is generated from the aggregated volume. To sum up, the essence of monocular compensation is to obtain a better depth distribution, which improves the performance. 
I am wondering if I understanded your design correctly.

**Comment by Tai-Wang** [comment]
Exactly. From our observation of the experimental results, it seems like that. If we only use the stereo volume for the subsequent 3D detection, adding the monocular compensated cost volume may be more important.

**Comment by shuxiusuxiu** [comment]
Thanks!
